/**
 * AI chat state that outlives the chat page.
 *
 * Replies are generated by server-side runs (see server/services/chat-runs.service.ts) and
 * followed over the shared WebSocket, so leaving the page, switching sessions or losing the
 * connection never loses a reply: on return / reconnect we resubscribe with the last seen
 * sequence number and the server replays what we missed. Each session has its own thread,
 * so several sessions can generate at the same time.
 */
import { defineStore } from 'pinia';
import { ref, computed, watch } from 'vue';
import { chatSocket, type SocketState } from '../api/chat-socket';
import { apiGetSessions, apiGetSession, apiDeleteSession, type SessionMeta } from '../api/chat.api';
import { useAuthStore } from './use-auth-store';
import type { ToolDisplay } from '../../shared/types/tool-display.types';
import type { ChatErrorInfo } from '../../shared/types/chat-error.types';
import type { ChatRunInfo, ChatRunStatus, ChatStartRequest, ChatWsServerMessage } from '../../shared/types/chat-run.types';

export interface ChatMsg {
  role: 'user' | 'assistant' | 'tool';
  content: string;
  thinking?: string;
  thinkingOpen?: boolean;
  toolName?: string;
  toolArgs?: Record<string, unknown>;
  /** Engine data behind a manually-run tool's interpretation */
  toolRaw?: string;
  /** Result regenerated from stored args (older versions saved only the call) */
  recomputed?: boolean;
  /** Structured payload for rich tool views */
  toolDisplay?: ToolDisplay;
  /** Failed turn — rendered as an error card, never as reply text */
  error?: ChatErrorInfo;
  toolOpen?: boolean;
  userTriggered?: boolean;
  /** Thumbnail data URIs / image URLs for display */
  imagePreviews?: string[];
}

interface ThreadRun {
  runId: string;
  status: ChatRunStatus;
  /** Last applied event; resubscribing asks for everything after it */
  lastSeq: number;
  endedAt?: number;
}

export interface ChatThread {
  /** sessionId, or `draft:n` until the server assigns one */
  key: string;
  sessionId?: string;
  messages: ChatMsg[];
  tokenEstimate: number;
  /** Waiting for the server to accept the message */
  sending: boolean;
  /** Stop pressed before the run id was known */
  stopRequested?: boolean;
  run: ThreadRun | null;
}

export interface SendOptions {
  text: string;
  mode: 'fc' | 'plain';
  images?: string[];
  presetTools?: ChatStartRequest['presetTools'];
  enableThinking?: boolean;
  profileId?: string;
}

/** Error for failures the server couldn't describe (e.g. the connection dropped). */
export function transportError(detail: string): ChatErrorInfo {
  return {
    kind: 'network', title: '连接中断', retryable: true,
    message: '与服务器的连接中断了，这次回复没能完成。',
    hint: '请检查网络后重试。', detail,
  };
}

function sendError(detail: string): ChatErrorInfo {
  return {
    kind: 'network', title: '消息没有发出', retryable: true,
    message: detail || '发送失败', hint: '可以稍后点击重试。',
  };
}

function toMsgs(list: Awaited<ReturnType<typeof apiGetSession>>['messages']): ChatMsg[] {
  return list
    .filter((m) => m.role === 'user' || m.role === 'assistant' || m.role === 'tool')
    .map((m) => ({
      role: m.role as ChatMsg['role'],
      content: m.content,
      thinking: m.thinking,
      thinkingOpen: false,
      toolName: m.toolName,
      toolArgs: m.toolArgs,
      toolRaw: m.toolRaw,
      recomputed: m.recomputed,
      toolDisplay: m.toolDisplay,
      error: m.error,
      toolOpen: false,
      userTriggered: m.userTriggered,
      imagePreviews: m.images?.length ? m.images : undefined,
    }));
}

/** How long after a reply finished the chat page still reopens on that conversation */
const RESUME_WINDOW_MS = 30 * 60 * 1000;

export const useChatStore = defineStore('chat', () => {
  const sessions = ref<SessionMeta[]>([]);
  const threads = ref<Record<string, ChatThread>>({});
  /** Thread on screen; null = welcome page (a new conversation) */
  const currentKey = ref<string | null>(null);
  /** Runs the server reports as generating, by sessionId (covers other tabs, reloads) */
  const serverRuns = ref<Record<string, ChatRunInfo>>({});
  const socketState = ref<SocketState>('idle');
  /** Bumped on every change to the visible thread (the page follows it to scroll) */
  const tick = ref(0);
  let draftSeq = 0;
  let initialized = false;

  const current = computed(() => (currentKey.value ? threads.value[currentKey.value] || null : null));
  const messages = computed<ChatMsg[]>(() => current.value?.messages || []);
  const currentSessionId = computed(() => current.value?.sessionId);
  const isBusy = (t: ChatThread | null | undefined) => !!t && (t.sending || t.run?.status === 'running');
  const busy = computed(() => isBusy(current.value));
  /** Sessions with a reply in progress (sidebar indicators) */
  const runningIds = computed(() => {
    const ids = new Set(Object.keys(serverRuns.value));
    for (const t of Object.values(threads.value)) if (t.sessionId && isBusy(t)) ids.add(t.sessionId);
    return ids;
  });
  const runningCount = computed(() => runningIds.value.size
    + Object.values(threads.value).filter((t) => !t.sessionId && isBusy(t)).length);

  function newThread(key: string, sessionId?: string): ChatThread {
    threads.value[key] = { key, sessionId, messages: [], tokenEstimate: 0, sending: false, run: null };
    return threads.value[key];
  }
  const threadByRun = (runId: string) => Object.values(threads.value).find((t) => t.run?.runId === runId);
  const bump = (t: ChatThread) => { if (t.key === currentKey.value) tick.value++; };

  // ── Lifecycle ──

  function init() {
    if (initialized) return;
    initialized = true;
    chatSocket.on(handle);
    chatSocket.onState((s) => { socketState.value = s; });
    chatSocket.connect();
    void loadSessions();
    // Another account must not see this one's conversations
    const auth = useAuthStore();
    watch(() => auth.user?.userId, (id, prev) => {
      if (id === prev) return;
      reset();
      if (id) { chatSocket.connect(); void loadSessions(); } else chatSocket.disconnect();
    });
  }

  function reset() {
    threads.value = {};
    sessions.value = [];
    serverRuns.value = {};
    currentKey.value = null;
  }

  /** Called when the chat page opens: resume a recent / in-progress conversation, else welcome. */
  function enterPage() {
    init();
    const t = current.value;
    const recent = t?.run && (t.run.status === 'running' || Date.now() - (t.run.endedAt || 0) < RESUME_WINDOW_MS);
    if (!t || !(isBusy(t) || recent)) currentKey.value = null;
  }

  async function loadSessions() {
    try { sessions.value = await apiGetSessions(); } catch { /* keep the old list */ }
  }

  // ── Sessions ──

  function openWelcome() {
    currentKey.value = null;
  }

  async function openSession(sid: string, opts: { force?: boolean } = {}) {
    currentKey.value = sid;
    const existing = threads.value[sid];
    // A thread that is live (or already loaded) is the freshest view we have
    if (existing && (isBusy(existing) || (!opts.force && existing.messages.length))) { tick.value++; return; }
    const data = await apiGetSession(sid);
    const t = threads.value[sid] || newThread(sid, sid);
    if (isBusy(t)) return; // a send started while we were loading
    t.messages = toMsgs(data.messages);
    t.tokenEstimate = data.tokenEstimate || 0;
    attachServerRun(t);
    if (currentKey.value === sid) tick.value++;
  }

  /**
   * The server is generating for this session (started before a reload, or in another tab):
   * follow it. The session file already holds the user message; the reply is rebuilt from
   * the run's events.
   */
  function attachServerRun(t: ChatThread) {
    const run = t.sessionId ? serverRuns.value[t.sessionId] : undefined;
    if (!run || run.status !== 'running' || t.run?.runId === run.runId) return;
    if (t.messages[t.messages.length - 1]?.role !== 'user') return; // reply already persisted
    t.messages.push({ role: 'assistant', content: '', thinkingOpen: false });
    t.run = { runId: run.runId, status: 'running', lastSeq: 0 };
    chatSocket.subscribe(run.runId, 0);
  }

  async function deleteSession(sid: string) {
    await apiDeleteSession(sid);
    sessions.value = sessions.value.filter((s) => s.sessionId !== sid);
    delete threads.value[sid];
    delete serverRuns.value[sid];
    if (currentKey.value === sid) currentKey.value = null;
  }

  // ── Sending ──

  async function send(o: SendOptions) {
    let t = current.value;
    if (isBusy(t)) return;
    if (!t) {
      t = newThread(`draft:${++draftSeq}`);
      currentKey.value = t.key;
    }
    t.messages.push({ role: 'user', content: o.text || `🖼️ [图片×${o.images?.length || 0}]`, imagePreviews: o.images?.length ? o.images : undefined });
    t.messages.push({ role: 'assistant', content: '', thinking: o.enableThinking ? '' : undefined, thinkingOpen: false });
    t.sending = true;
    t.stopRequested = false;
    t.run = null;
    tick.value++;

    try {
      const run = await chatSocket.start({
        mode: o.mode,
        message: o.text || '请看图片',
        sessionId: t.sessionId,
        enableThinking: o.enableThinking,
        profileId: o.profileId,
        imagesBase64: o.images?.length ? o.images : undefined,
        presetTools: o.presetTools,
        clientTime: new Date().toISOString(),
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      });
      t = threads.value[t.key] || t;
      t.sending = false;
      if (!t.sessionId) adoptSession(t, run.sessionId);
      // The replay that follows `started` may already have filled the run in
      if (!t.run || t.run.runId !== run.runId) t.run = { runId: run.runId, status: run.status, lastSeq: 0 };
      if (t.stopRequested) chatSocket.stop(run.runId);
      if (!sessions.value.some((s) => s.sessionId === run.sessionId)) void loadSessions();
    } catch (err) {
      t.sending = false;
      const last = t.messages[t.messages.length - 1];
      if (last?.role === 'assistant') last.error = sendError((err as Error).message);
      bump(t);
    }
  }

  /** A draft got its sessionId: re-key the thread (and keep it on screen). */
  function adoptSession(t: ChatThread, sid: string) {
    const draftKey = t.key;
    delete threads.value[draftKey];
    t.key = sid;
    t.sessionId = sid;
    threads.value[sid] = t;
    if (currentKey.value === draftKey) currentKey.value = sid;
  }

  function stop() {
    const t = current.value;
    if (!t) return;
    if (t.run?.status === 'running') chatSocket.stop(t.run.runId);
    else if (t.sending) t.stopRequested = true;
  }

  /** Remove messages from index `from` on (retrying a failed turn). */
  function truncate(from: number) {
    current.value?.messages.splice(from);
  }

  // ── Run events ──

  function handle(msg: ChatWsServerMessage) {
    switch (msg.type) {
      case 'hello': {
        const live: Record<string, ChatRunInfo> = {};
        for (const r of msg.runs) if (r.status === 'running') live[r.sessionId] = r;
        serverRuns.value = live;
        const known = new Set(msg.runs.map((r) => r.runId));
        for (const t of Object.values(threads.value)) {
          if (t.run?.status !== 'running') continue;
          // Pick up where we left off; a run the server forgot can only be re-read from disk
          if (known.has(t.run.runId)) chatSocket.subscribe(t.run.runId, t.run.lastSeq);
          else endRunFromDisk(t);
        }
        void loadSessions();
        return;
      }
      case 'runs': {
        const r = msg.run;
        if (msg.change === 'started') {
          serverRuns.value[r.sessionId] = r;
          // Started elsewhere (another tab) on a conversation we have open: follow it
          const t = threads.value[r.sessionId];
          if (t && !isBusy(t) && t.key === currentKey.value) void openSession(r.sessionId, { force: true });
          else if (t && !isBusy(t)) delete threads.value[r.sessionId];
        } else {
          delete serverRuns.value[r.sessionId];
          void loadSessions();
        }
        return;
      }
      case 'replay': {
        const t = threadByRun(msg.run.runId);
        if (!t) return;
        for (const e of msg.events) applyEvent(t, e.seq, e.data);
        return;
      }
      case 'event': {
        const t = threadByRun(msg.runId);
        if (!t?.run) return;
        if (msg.event.seq > t.run.lastSeq + 1) { chatSocket.subscribe(msg.runId, t.run.lastSeq); return; }
        applyEvent(t, msg.event.seq, msg.event.data);
        return;
      }
      case 'error': {
        const t = msg.runId ? threadByRun(msg.runId) : undefined;
        if (t) endRunFromDisk(t);
        return;
      }
    }
  }

  function applyEvent(t: ChatThread, seq: number, d: Record<string, any>) {
    const run = t.run;
    if (!run || seq <= run.lastSeq) return;
    run.lastSeq = seq;
    const msgs = t.messages;
    let last = msgs[msgs.length - 1];
    if (last?.role !== 'assistant') {
      last = { role: 'assistant', content: '', thinkingOpen: false };
      msgs.push(last);
    }
    if (d.toolCall) {
      const tc = d.toolCall;
      msgs.splice(msgs.length - 1, 0, {
        role: 'tool', content: tc.result || `调用 ${tc.name}`, toolName: tc.name, toolArgs: tc.args, toolDisplay: tc.display, toolOpen: false,
      });
    }
    if (d.thinking) {
      last.thinking = (last.thinking || '') + d.thinking;
      if (!last.content) last.thinkingOpen = true;
    }
    if (d.content) {
      // Collapse the reasoning once the answer starts
      if (!last.content && last.thinking) last.thinkingOpen = false;
      last.content += d.content;
    }
    if (d.error) last.error = d.errorInfo || transportError(String(d.error));
    if (d.runEnd) {
      run.status = (d.status as ChatRunStatus) || 'done';
      run.endedAt = Date.now();
      delete serverRuns.value[t.sessionId || ''];
      void refreshMeta(t);
    }
    bump(t);
  }

  /** After a reply: update the sidebar (AI title, time) and the context estimate. */
  async function refreshMeta(t: ChatThread) {
    void loadSessions();
    if (!t.sessionId) return;
    try { t.tokenEstimate = (await apiGetSession(t.sessionId)).tokenEstimate || 0; } catch { /* non-critical */ }
  }

  /** The run is gone from the server (expired / restarted): whatever was saved is the truth. */
  function endRunFromDisk(t: ChatThread) {
    if (t.run) { t.run.status = 'done'; t.run.endedAt = Date.now(); }
    if (!t.sessionId) return;
    if (t.key === currentKey.value) void openSession(t.sessionId, { force: true }).catch(() => {});
    else delete threads.value[t.key];
  }

  return {
    sessions, threads, currentKey, current, messages, currentSessionId, busy, runningIds, runningCount,
    socketState, tick,
    init, enterPage, loadSessions, openWelcome, openSession, deleteSession, send, stop, truncate,
  };
});
